### ISSUE TITLE
MSMapClusteringDelegate needs a removeObserver call to balance addObserver

### ISSUE THREAD

**Issue by wayneljw** [MarcoSero/MSMapClustering#1]
Thanks for the great class.

Suggestion in MSMapClusteringDelegate.m

We need this to balance the "addObserver call. Otherwise, the app would crash when the map view is unloaded.
- (void)dealloc
  {
  [[NSNotificationCenter defaultCenter] removeObserver:self name:@"AnnotationsAdded" object:nil];
  }

**Comment by MarcoSero** [comment]
Solved with commit https://github.com/MarcoSero/MSMapClustering/commit/79069ae029459e8d008d96bda3d07580d4623598
