### ISSUE TITLE
MSMapClustering may require better removeMSAnnotation or removeMSAnnotations methods

### ISSUE THREAD

**Issue by wayneljw** [MarcoSero/MSMapClustering#2]
Currently, MSMapClustering has addMSAnnotation and addMSAnnotations to force the annotations added to "((MSMapClusteringDelegate *)self.delegate)._allAnnotationsMapView". This is good.

But we don't have good "remove annotation(s)" methods to handle this quickly.

Currently, what I do is writing 2 lines in my main view controller:
(Note: this example is doing "removing all annotations on the map)

[_mapView removeAnnotations:[_mapView annotations]];
[((MSMapClusteringDelegate *)_mapView.delegate)._allAnnotationsMapView removeAnnotations:[((MSMapClusteringDelegate *)_mapView.delegate)._allAnnotationsMapView annotations]];

It is better if we could have 2 methods
removeMSAnnotation
removeMSAnnotations

**Comment by MarcoSero** [comment]
Now you can remove annotations https://github.com/MarcoSero/MSMapClustering/commit/558f3d8b5164795990b7e1aa0419a4bb723a8a3d

I haven't tested it properly, feel free to re open the issue if it doesn't work.
